Hackerank/Hackerank/urls.py
from django.contrib import admin
from django.urls import path,include
from quiz import views
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView
router=DefaultRouter()
router.register("api/v1/categories",views.CategoriesView,basename="categories")
router.register("api/v1/questions",views.QuestionsView,basename="questions")

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/v1/token/",TokenObtainPairView.as_view()),
    path("api/v1/token/refresh/",TokenRefreshView.as_view()),
    path("web/",include("quizapp.urls"))
    # path("api/v1/token/",ObtainAuthToken.as_view())
]+router.urls

Hackerank/quizapp/urls.py
from django.urls import path
from quizapp import views
from django.views.generic import TemplateView
urlpatterns=[
    path("register",views.SignUpView.as_view(),name="signup"),
    path("login",views.SignInView.as_view(),name="signin"),
    path("signout",views.signout_view,name="signout"),
    path("home",views.HomeView.as_view(),name="home"),
    path("subhome",views.HomeSubView.as_view(),name="home-frst"),
    path("quizes/home",views.QuizHomeView.as_view(),name="quiz-home"),
    path("questions/all/<str:cat>/<str:mode>/",views.QuestListView.as_view(),name="question-list"),
    path("quiz/record/",views.QuizRecordView.as_view(),name="quiz-record")
]

Hackerank/quiz/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class Category(models.Model):
    name=models.CharField(max_length=100,unique=True)
    is_active=models.BooleanField(default=True)


    def __str__(self) -> str:
        return self.name
    
class Questions(models.Model):
    category=models.ForeignKey(Category,on_delete=models.DO_NOTHING)   
    options=(
        ('easy','easy'),
        ('medium','medium'),
        ('hard','hard')
           ) 
    mode=models.CharField(max_length=200,choices=options,default='easy')
    mark=models.PositiveIntegerField(default=2)
    question=models.CharField(max_length=200)

    @property
    def choices(self):
        return Answers.objects.filter(question=self)

    @property
    def answer(self):
        return Answers.objects.get(question=self,is_correct=True)
    
    def __str__(self) -> str:
        return self.question
    

class Answers(models.Model):
    question=models.ForeignKey(Questions,on_delete=models.CASCADE)
    options=models.CharField(max_length=200) 
    is_correct=models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.options
    
class QuizRecord(models.Model):
    total_mark=models.PositiveIntegerField()
    right_answer_count=models.PositiveIntegerField()
    wrong_answer_count=models.PositiveIntegerField()
    user=models.ForeignKey(User,on_delete=models.DO_NOTHING)
    date=models.DateField(auto_now_add=True)

Hackerank/quizapp/models.py
from django.db import models

# Create your models here.

Hackerank/quizapp/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class RegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=["email","username","password1","password2"]

class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)

Hackerank/quizapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from quizapp.forms import RegistrationForm,LoginForm
from django.views.generic import CreateView,View,FormView,TemplateView,ListView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from quiz.models import Category,Questions,QuizRecord
import random

# Create your views here.

class SignUpView(CreateView):
    form_class=RegistrationForm
    model=User
    template_name="register.html"
    success_url=reverse_lazy("signin")
    def form_valid(self, form):
        messages.success(self.request,"account has been created")
        return super().form_valid(form)
    def form_invalid(self, form):
        messages.error(self.request,"failed to create account")
        return super().form_invalid(form)

class SignInView(FormView):
    form_class=LoginForm
    template_name="login.html"

    def post(self,request,*args,**kwargs):
        form=LoginForm(request.POST)
        if form.is_valid():
            uname=form.cleaned_data.get("username")
            pwd=form.cleaned_data.get("password")
            usr=authenticate(request,username=uname,password=pwd)
            if usr:
                login(request,usr)
                return redirect("home")
        return render(request,self.template_name,{"form":form})
def signout_view(request,*args,**kwargs):
    logout(request)
    return redirect("signin")
    
class HomeView(TemplateView):
    template_name="home.html"

class HomeSubView(TemplateView):
    template_name="home1.html"

class QuizHomeView(View):
    def get(self,request,*args,**kwargs):
        qs=Category.objects.all()
        return render(request,"quiz-home.html",{"cats":qs})
    
    def post(self,request,*args,**kwargs):
        cat=request.POST.get("category")
        mode=request.POST.get("mode")
        print(cat,mode)
        return redirect("question-list",cat=cat,mode=mode)
    
from django.db.models import Sum
class QuestListView(View):
    def get(self,request,*args,**kwargs):
        category=kwargs.get("cat")
        mode=kwargs.get("mode")
        qs=list(Questions.objects.filter(mode=mode,category__name=category))
        
        
       
        # grand_total=0
        # for q in qob:
        #     grand_total+=q.mark
        # print(grand_total)
        random.shuffle(qs)
        return render(request,"question-list.html",{"questions":qs})
    
    def post(self,request,*args,**kwargs):
        data=request.POST.dict()
        data.pop('csrfmiddlewaretoken')
        question_attended=len(data)
        total_mark=0
        wrong_answer_count=0

        for q,ans in data.items():
            question=Questions.objects.get(question=q)
            right_answer_obj=question.answer
            if(right_answer_obj.options==ans):
                total_mark=total_mark+question.mark
            else:
                wrong_answer_count+=1
            right_answer_count=question_attended-wrong_answer_count

        print(total_mark,question_attended,wrong_answer_count,right_answer_count)
        category=kwargs.get("cat")
        mode=kwargs.get("mode")
        result=''
        total=Questions.objects.filter(mode=mode,category__name=category).aggregate(Sum("mark")).get('mark__sum')
        if total/2 <= total_mark:
            result='passed the exam'
        else:
            result='failed the exam'
        # total=total.get('mark___sum')
        print(total)
        data=QuizRecord.objects.create(total_mark=total_mark,right_answer_count=right_answer_count,wrong_answer_count=wrong_answer_count,user=request.user)
        return render(request,"quiz-mark.html",{'total_mark':total_mark,"question_attended":question_attended,'result':result})
    


class QuizRecordView(ListView):
    model=QuizRecord
    template_name="quiz-record.html"
    context_object_name="records"


    def get_queryset(self):
        return QuizRecord.objects.filter(user=self.request.user)

Hackerank/quizapp/templates/home.html
{%extends 'index.html'%}
{%block body%}
<h1>Welcome {{request.user}}</h1>
    <a href="{%url 'quiz-home'%}" class="btn btn-info">Start Quiz</a>
    <a href="{%url 'quiz-record'%}" class="btn btn-info">History</a>
{%endblock%}

Hackerank/quizapp/templates/home1.html
{%extends 'index.html'%}
{%block body%}
<h1>Welcome {{request.user}}</h1>
    <a href="{%url 'quiz-home'%}" class="btn btn-info">Start Quiz</a>
    <a href="{%url 'quiz-record'%}" class="btn btn-info">History</a>
{%endblock%}

Hackerank/quizapp/templates/index.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">QuizApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html"></a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html"></a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'home-frst'%}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'signout'%}">Sign Out</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({%static 'assets/img/home-bg.jpg'%})">
            
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                   {%block body%}
                   {%endblock%}
                   
                   
                    
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"></div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
    </body>
</html>

Hackerank/quizapp/templates/login.html
<!DOCTYPE html>
{%load static%}
<!-- Coding By CodingNepal - youtube.com/codingnepal -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    <link rel="stylesheet" href="{%static 'css/loginstyle.css'%}">
  </head>
  <body>
    <div class="center">
      <h1>Login</h1>
      <form method="post">
        {%csrf_token%}
        <div class="txt_field">
          <input type="text" name="username" required>
          <span></span>
          <label>Username</label>
        </div>
        <div class="txt_field">
          <input type="password" name="password" required>
          <span></span>
          <label>Password</label>
        </div>
        <div class="pass">Forgot Password?</div>
        <input type="submit" value="Login">
        <div class="signup_link">
          Not a member? <a href="{%url 'signup'%}">Signup</a>
        </div>
      </form>
    </div>

  </body>
</html>

Hackerank/quizapp/templates/question-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container border rounded p-2 mt-4">
       <form action="" method="post">
        {%csrf_token%}
        {%for q in questions%}
        <div class="border border-bottom mb-3">
            <h4>{{forloop.counter}} {{q.question}} marks({{q.mark}})</h4>

           <div style="height:80px;">
            {%for ch in q.choices%}
           <span class="p-2" ><input type="radio" name="{{q}}"value="{{ch}}">{{ch}}</span>
            
            
           {%endfor%}
           </div>

        </div>
        {%endfor%}
        <div class="text-center">
            <button type="sumbit" class="btn btn-info">submit</button>
        </div>
        
       </form>
    </div>
</body>
</html>

Hackerank/quizapp/templates/quiz-home.html
{%extends 'index.html'%}
{%block body%}
<div class="container">
    <div class="row  ">
        <div class="col-0"></div>
        <div class="col-12 shadow p-3  ">
            <form action="" method="post">
                {%csrf_token%}
                <label for="id_category" class="form-text">Select a category</label>
                <select name="category" id="id_category" class="form-select  mb-2">
                    {%for cat in cats%}
                    <option value="{{cat.name}}">{{cat.name}}</option>

                    {%endfor%}

                </select>
                <label for="id_mode" class="form-text">Select a mode</label>
                <select name="mode" id="id_mode" class="form-select  mb-2">
                <option value="easy">easy</option>
                <option value="medium">medium</option>
                <option value="hard">hard</option>
                </select>
                <div class="text-center">
                    <input type="submit" value="lets start" class="btn btn-outline-success"> 
                </div>
                
            </form>
        </div>
        <div class="col-0"></div>
    </div>
</div>
{%endblock%}

Hackerank/quizapp/templates/quiz-mark.html
{%extends 'index.html'%}
{%block body%}
<div class="container">
    <div class="row">
        <div class="col-0"></div>
        <div class="col-12">
            <h1 class="text-center">Marks</h1>
            <h1 class="text-center">Total marks obtained {{total_mark}}</h1>
            <h1 class="text-center">Questions attended {{question_attended}}</h1>
            <h1 class="text-center">Status: {{result}}</h1>
        </div>
        <div class="col-1"></div>
    </div>

</div>
{%endblock%}

Hackerank/quizapp/templates/quiz-record.html
{%extends 'index.html'%}
{%block body%}
<div class="container">
    <div class="row mt-5">
        <div class="col-0"></div>
        <div class="col-12">
        <table class="table table-striped">
            <tr>
              <th>Total mark</th>
              <th>Right Answer Count</th>
              <th>Wrong answer count</th>
              <th>Date</th>
              
            </tr>
            {%for r in records%}
             <tr>
                 <td>{{r.total_mark}}</td>
                 <td>{{r.right_answer_count}}</td>
                 <td>{{r.wrong_answer_count}}</td>
                 <td>{{r.date}}</td>
                 
                 
                 
             </tr>
            {%endfor%}
        </table>
        </div>
        <div class="col-0"></div>
    </div>

{%endblock%}

Hackerank/quizapp/templates/register.html
<!DOCTYPE html>
{%load static%}
<!-- Coding By CodingNepal - youtube.com/codingnepal -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    <link rel="stylesheet" href="{%static 'css/loginstyle.css'%}">
  </head>
  <body>
    <div class="center">
      <h1>Register</h1>
      <form method="post">
        {%csrf_token%}
        <div class="txt_field">
          <input type="text" name="username" required>
          <span></span>
          <label>Username</label>
        </div>
        <div class="txt_field">
            <input type="email" name="email" required>
            <span></span>
            <label>Email</label>
          </div>
        <div class="txt_field">
          <input type="password" name="password1" required>
          <span></span>
          <label>Password</label>
        </div>
          <div class="txt_field">
            <input type="password" name="password2" required>
            <span></span>
            <label>Confirm Password</label>
        </div>
        <div class="pass"></div>
        <input type="submit" value="Register">
        <div class="signup_link">
          Already a member? <a href="{%url 'signin'%}">SignIn</a>
        </div>
      </form>
    </div>

  </body>
</html>